### ISSUE TITLE
Numbers instead of names in Thing ZIP file

### ISSUE THREAD

**Issue by DrLex0** [DrLex0/ThingiverseIssues#12]
Downloaded Thing ZIP files have a number as file name, instead of the Thing name.

**Comment by aeakin1** [comment]
Additionally, the zip keeps its original Number (I am guessing it is the Object ID) even if the file is moved, renamed or updated. The OID changes for the item but not the ZIP file.

**Comment by DrLex0** [comment]
This seems to be fixed.
