### ISSUE TITLE
Slow and unreliable website: 500, 503, 504 errors

### ISSUE THREAD

**Issue by DrLex0** [DrLex0/ThingiverseIssues#2]
This is probably due to the general state of server overload that also causes many other issues.

**Comment by DrLex0** [comment]
This is particularly bad right now, and 404 errors have joined the collection of possible errors.
During the times that I manage to open my dashboard amidst this storm of failures, I can see that the activity level is much lower than before, which makes sense if it is this difficult for everyone to merely view pages on the site.

**Comment by DrLex0** [comment]
It looks like something has finally been improved since yesterday. The site was almost unreachable for an hour and when it came back, it seemed much more reliable and responsive. I'll wait a few more days and I hope I can then finally close this issue.

**Comment by DrLex0** [comment]
Unfortunately I still cannot close this issue because Thingiverse is again becoming noticeably slower. I haven't seen any 50x errors yet, but I expect them to return as well if things keep becoming slower…

**Comment by w3ace** [comment]
They turned preview generation back on for the STL files.  This could account for a new slow down.  Drawing this logic to it's conclusion leads me too a sad premise:  All of their troubles might be able to be solved VERY SIMPLY with more hardware dedicated to processing STL files into image previews.

**Comment by DrLex0** [comment]
The site is much faster now and I haven't seen any 50x errors in a long time. Thanks to the admins for fixing this and giving me some hope that the site isn't being deliberately broken down. I hope I won't need to reopen this issue.
