### ISSUE TITLE
Comment editing causes "This comment is currently flagged for moderation."

### ISSUE THREAD

**Issue by ArtieH** [DrLex0/ThingiverseIssues#20]
Comment editing causes "This comment is currently flagged for moderation."
Making two small edits of a 1 character insert to an existing comment within 1 minute causes the comment to be flagged.
This is unacceptable due to the caused aggravation, loss of information, and duplicate posts being created to back fill the lost version.
Recreated comments are usually of lower quality to the membership than the original.

**Comment by DrLex0** [comment]
This is actually the same as #16. I'll extend the description of that one.

**Comment by ArtieH** [comment]
Thanks. Sorry missed that.
