### ISSUE TITLE
Uploads often fail invisibly

### ISSUE THREAD

**Issue by DrLex0** [DrLex0/ThingiverseIssues#3]
This is both the case when submitting a new Thing or a Make. To the user, it seems the upload is working but in the end the file is not there. For Makes, this typically results in in an empty Make without any images. This is probably caused by the unreliable servers (#2).

**Comment by positron96** [comment]
Mine sometimes appear as 0-sized files and "Thing files" page then fails to load (its text contents load, but everything else, css, js does not work)

**Comment by DrLex0** [comment]
I haven't seen this in a while (then again, I haven't uploaded much either). Since it was most likely tied to #2, it can be closed.
